Fix tooltip
UBC-MDS/DSCI-532_2024_1_TBtracker pull request #114
Opened 2024-04-17 16:48 UTC by sandygross

Hi, I added some things for the tooltip. Please review!

2024-04-17 18:54 UTC, sean-m-mckay requested changes

2024-04-17 18:54 UTC, sean-m-mckay commented on src/callbacks.py
> +            opacity=alt.condition(highlight, alt.value(0.8), alt.value(0.5)),
This can just be the following, since we defined this in a variable
```suggestion
            opacity=opacity
```

2024-04-17 18:54 UTC, sean-m-mckay commented on src/utils.py
> +    }
You can remove this, since it's set in the dcc.Graph object which wraps the plotly plot

2024-04-17 18:54 UTC, sean-m-mckay commented on src/utils.py
> +    fig.show(config=config)
This is what is making the line plots dissapear 

```suggestion
    return fig
```

2024-04-18 05:42 UTC, sandygross commented on src/callbacks.py
> +            opacity=alt.condition(highlight, alt.value(0.8), alt.value(0.5)),
Thanks Sean! Fixed it

2024-04-18 21:15 UTC, sean-m-mckay approved these changes
LGTM!

2024-04-18 21:48 UTC, merged