Add Section 4
UBC-MDS/DSCI-532_2024_1_TBtracker pull request #16
Opened 2024-03-29 02:56 UTC by zywkloo

2024-03-29 03:38 UTC, sean-m-mckay approved these changes
LGTM!

2024-03-29 03:40 UTC, sean-m-mckay commented on img/sketchup.png
We have an updated image for the sketchup [here] (https://private-user-images.githubusercontent.com/20444993/317561676-ff9394cd-8954-4795-8f7a-3cc743e40c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODM4MDIsIm5iZiI6MTcxMTY4MzUwMiwicGF0aCI6Ii8yMDQ0NDk5My8zMTc1NjE2NzYtZmY5Mzk0Y2QtODk1NC00Nzk1LThmN2EtM2NjNzQzZTQwYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYTk5YzNhNDk4ZWRjYTdmMmE4NDJhNGQ0OTM3OWZiMzVlZjFkZThlMWUwZDBmMzkwZmIyODYwZjQ1YjE1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9e6BfqCdy4HuM2_IcPp0iFFER_GFTb55Ys-cwOFDb5g)

2024-03-29 03:41 UTC, sean-m-mckay requested changes
The main page sketchup was updated to use toggles instead of radio buttons and to be consistent with the second page. Otherwise description looks good

2024-03-30 06:22 UTC, sandygross approved these changes

2024-03-30 06:37 UTC, merged